<a href="https://colab.research.google.com/github/gl-24/my-NLP/blob/main/day-8/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [3]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 578.0 MB 16 kB/s 
     |████████████████████████████████| 438 kB 63.3 MB/s 
     |████████████████████████████████| 5.9 MB 55.6 MB/s 
     |████████████████████████████████| 1.7 MB 53.3 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: keras
    Found existing installation: keras 2.8.0
    Uninstalling keras-2.8.0:
      Successfully uninstalled keras-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.5

In [4]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [5]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [16]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [17]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[482, 5708, 6857, 6558], [482, 5708, 6857, 8599], [482, 6258, 6857, 1473], [5575, 7360, 3036, 9666, 7570], [5575, 7360, 3036, 9666, 8124], [4076, 482, 5391, 6857, 9688], [5669, 1498, 2489, 9666]]


### Word Embedding Represntation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 112 100 437 239]
 [  0   0   0   0 112 100 437 436]
 [  0   0   0   0 112 235 437  86]
 [  0   0   0 100 446  12 132 128]
 [  0   0   0 100 446  12 132 122]
 [  0   0   0 400 112 337 437 249]
 [  0   0   0   0 451 457  28 132]]


In [13]:
## 10 feature dimesnions
dim=10


In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [18]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 112, 100, 437, 239], dtype=int32)

In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 71ms/step


array([[-0.04319935, -0.01780663,  0.04679135, -0.04454088,  0.03012249,
        -0.00124114, -0.03537669,  0.02287496,  0.00891273,  0.02533047],
       [-0.04319935, -0.01780663,  0.04679135, -0.04454088,  0.03012249,
        -0.00124114, -0.03537669,  0.02287496,  0.00891273,  0.02533047],
       [-0.04319935, -0.01780663,  0.04679135, -0.04454088,  0.03012249,
        -0.00124114, -0.03537669,  0.02287496,  0.00891273,  0.02533047],
       [-0.04319935, -0.01780663,  0.04679135, -0.04454088,  0.03012249,
        -0.00124114, -0.03537669,  0.02287496,  0.00891273,  0.02533047],
       [-0.04056505, -0.04096148,  0.04391975,  0.03530758, -0.00528944,
        -0.03741743,  0.02493669, -0.04273413,  0.0031963 ,  0.02614028],
       [ 0.01831206,  0.01213298, -0.03471022, -0.01358557, -0.04395637,
        -0.04712961, -0.04895685,  0.0171063 ,  0.04751246,  0.00370646],
       [ 0.02560237,  0.01836565,  0.01119777, -0.03231386,  0.02636543,
         0.03202537,  0.0432794 ,  0.00465319

In [20]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 36ms/step
[[[-4.31993492e-02 -1.78066269e-02  4.67913486e-02 -4.45408821e-02
    3.01224925e-02 -1.24113634e-03 -3.53766903e-02  2.28749551e-02
    8.91273096e-03  2.53304727e-02]
  [-4.31993492e-02 -1.78066269e-02  4.67913486e-02 -4.45408821e-02
    3.01224925e-02 -1.24113634e-03 -3.53766903e-02  2.28749551e-02
    8.91273096e-03  2.53304727e-02]
  [-4.31993492e-02 -1.78066269e-02  4.67913486e-02 -4.45408821e-02
    3.01224925e-02 -1.24113634e-03 -3.53766903e-02  2.28749551e-02
    8.91273096e-03  2.53304727e-02]
  [-4.31993492e-02 -1.78066269e-02  4.67913486e-02 -4.45408821e-02
    3.01224925e-02 -1.24113634e-03 -3.53766903e-02  2.28749551e-02
    8.91273096e-03  2.53304727e-02]
  [-4.05650511e-02 -4.09614816e-02  4.39197533e-02  3.53075750e-02
   -5.28943539e-03 -3.74174342e-02  2.49366872e-02 -4.27341349e-02
    3.19629908e-03  2.61402838e-02]
  [ 1.83120631e-02  1.21329799e-02 -3.47102173e-02 -1.35855675e-02
   -4.39563654e-02 -4.71296087e

In [21]:
embedded_docs[0]

array([  0,   0,   0,   0, 112, 100, 437, 239], dtype=int32)

In [22]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 17ms/step
[[-0.04319935 -0.01780663  0.04679135 -0.04454088  0.03012249 -0.00124114
  -0.03537669  0.02287496  0.00891273  0.02533047]
 [-0.04319935 -0.01780663  0.04679135 -0.04454088  0.03012249 -0.00124114
  -0.03537669  0.02287496  0.00891273  0.02533047]
 [-0.04319935 -0.01780663  0.04679135 -0.04454088  0.03012249 -0.00124114
  -0.03537669  0.02287496  0.00891273  0.02533047]
 [-0.04319935 -0.01780663  0.04679135 -0.04454088  0.03012249 -0.00124114
  -0.03537669  0.02287496  0.00891273  0.02533047]
 [-0.04056505 -0.04096148  0.04391975  0.03530758 -0.00528944 -0.03741743
   0.02493669 -0.04273413  0.0031963   0.02614028]
 [ 0.01831206  0.01213298 -0.03471022 -0.01358557 -0.04395637 -0.04712961
  -0.04895685  0.0171063   0.04751246  0.00370646]
 [ 0.02560237  0.01836565  0.01119777 -0.03231386  0.02636543  0.03202537
   0.0432794   0.00465319  0.01671257  0.03404951]
 [ 0.00688518  0.04682995 -0.01131562  0.00626719 -0.02362764 -0.02410745

In [23]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]